### PR TITLE
fix(pair_stable_bluna): use lp staked to generator as reward share

### LINKED ISSUE #184: Bluna stable pool
Rewards aren't distributed correctly if user transfers lp tokens

### PR DESCRIPTION
**Pull request by ShadoySV**
Fixes #184

Use lp token amount staked to the generator as the share for bluna rewards distribution

### CODE REVIEW

File: contracts/pair_stable_bluna/src/contract.rs [hunk 1]
```diff
@@ -1476,14 +1457,19 @@ pub fn migrate(deps: DepsMut, env: Env, _msg: MigrateMsg) -> Result<Response, Co
...
                 response
                     .messages
                     .push(get_bluna_reward_holder_instantiating_message(
                         deps.as_ref(),
                         &env,
                         &config.factory_addr,
-                    )?)
+                    )?);
+
+                BLUNA_REWARD_GLOBAL_INDEX.save(deps.storage, &cosmwasm_std::Decimal256::zero())?;
```
Comment (P-Yevhenii) [inline contracts/pair_stable_bluna/src/contract.rs:1472]: is we need to set BLUNA_REWARD_GLOBAL_USER_INDEX to zero?

Comment (ShadoySV) [reply contracts/pair_stable_bluna/src/contract.rs:1472]: Yes, otherwise we will get an error on reading it

Comment (ShadoySV) [reply contracts/pair_stable_bluna/src/contract.rs]: Replaced it with better approach

File: contracts/tokenomics/generator/src/contract.rs [hunk 2]
```diff
@@ -1480,6 +1562,45 @@ pub fn calculate_rewards(env: &Env, pool: &PoolInfo, cfg: &Config) -> StdResult<
 ///
 /// * **_msg** is the object of type [`MigrateMsg`].
 #[cfg_attr(not(feature = "library"), entry_point)]
-pub fn migrate(_deps: DepsMut, _env: Env, _msg: MigrateMsg) -> Result<Response, ContractError> {
-    Ok(Response::default())
+pub fn migrate(deps: DepsMut, _env: Env, _msg: MigrateMsg) -> Result<Response, ContractError> {
```
Comment (epanchee) [inline contracts/tokenomics/generator/src/contract.rs:1565]: I think we need to cover it with test

File: contracts/tokenomics/generator/src/lib.rs [hunk 3]
```diff
@@ -1,3 +1,4 @@
 pub mod contract;
 pub mod error;
+pub mod migration;
```
Comment (epanchee) [inline contracts/tokenomics/generator/src/lib.rs:3]: Imho we do not need it to be public.

File: contracts/tokenomics/generator/Cargo.toml [hunk 4]
```diff
@@ -1,6 +1,6 @@
 [package]
 name = "astroport-generator"
-version = "1.0.0"
+version = "1.1.1"
```
Comment (epanchee) [inline contracts/tokenomics/generator/Cargo.toml:3]: Since this PR is a fix we need to increase only patch version i.e I suggest 1.0.1 version.

File: contracts/pair_stable_bluna/src/contract.rs [hunk 5]
```diff
@@ -1899,7 +1931,7 @@ pub fn calc_user_reward(
     user_share: Uint128,
     total_share: Uint128,
     bluna_reward_global_index: cosmwasm_std::Decimal256,
-    bluna_reward_user_index: cosmwasm_std::Decimal256,
+    bluna_reward_user_index: Option<cosmwasm_std::Decimal256>,
```
[the remark this answers is not in the document]
Comment (ShadoySV) [reply contracts/pair_stable_bluna/src/contract.rs:1945]: Thanks

File: contracts/tokenomics/generator/src/contract.rs [hunk 6]
```diff
@@ -320,6 +325,7 @@ pub fn add(
     env: Env,
     lp_token: Addr,
     alloc_point: Uint64,
+    has_asset_rewards: bool,
```
[the remark this answers is not in the document]
Comment (ShadoySV) [reply contracts/tokenomics/generator/src/contract.rs:328]: Ok

File: contracts/tokenomics/generator/src/contract.rs (hunk 2 above)
Comment (ShadoySV) [reply contracts/tokenomics/generator/src/contract.rs:1565]: Yes, as well as the bluna rewards at all, we planned to do it a little later

File: contracts/tokenomics/generator/src/lib.rs (hunk 3 above)
Comment (ShadoySV) [reply contracts/tokenomics/generator/src/lib.rs:3]: True

File: contracts/tokenomics/generator/Cargo.toml (hunk 4 above)
Comment (ShadoySV) [reply contracts/tokenomics/generator/Cargo.toml:3]: That's a feature to claim asset rewards from pools. Will set it to 1.1.0

**Review by P-Yevhenii — APPROVED** [review]

File: contracts/tokenomics/generator/src/contract.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (wedancedalot) [reply contracts/tokenomics/generator/src/contract.rs:330]: it's not an object, just a bool type

[the remark this answers is not in the document]
Comment (ShadoySV) [reply contracts/tokenomics/generator/src/contract.rs:330]: True

File: contracts/tokenomics/generator/src/contract.rs [hunk 7]
```diff
@@ -868,6 +891,37 @@ pub fn deposit(
         vec![]
     };
 
+    let reward_msg = if pool.has_asset_rewards {
+        let total_share = match &pool.reward_proxy {
```
[the remark this answers is not in the document]
Comment (ShadoySV) [reply contracts/tokenomics/generator/src/contract.rs]: Done
