### PR TITLE
fix(pair_stable): reverse swap calculation

### LINKED ISSUE #168: Incorrect spread calculation for stable pool simulation
Seems like `spread_amount` is incorrectly calculated in `compute_offer_amount` function in stable pool
https://github.com/astroport-fi/astroport-core/blob/master/contracts/pair_stable/src/contract.rs#L1245

Looks like in calc_amount the ask amount is always lower then  offer amount, so we can't just swap the assets as that would mean offer is alway lower. We need to find a way to properly calculate offer amount

### PR DESCRIPTION
**Pull request by ShadoySV**
Fixes #168

### CODE REVIEW

File: contracts/pair_stable/src/math.rs [hunk 1]
```diff
@@ -26,12 +26,39 @@ pub fn calc_amount(balance_in: u128, balance_out: u128, amount_in: u128, amp: u6
...
+/// ## Params
+/// * **balance_in** is the object of type [`u128`].
+///
+/// * **balance_out** is the object of type [`u128`].
+///
+/// * **amount_out** is the object of type [`u128`].
+///
+/// * **amp** is the object of type [`u64`].
+pub fn calc_reverse_amount(
+    balance_in: u128,
```
Comment (wedancedalot) [inline contracts/pair_stable/src/math.rs:46]: maybe we need to rename the parameters into `offer_pool` and `ask_pool`, `ask_amount` to represent the actual values that needs to be passed

Comment (wedancedalot) [reply contracts/pair_stable/src/math.rs:46]: and maybe rename the function to `calc_offer_amount`, and do similar for `calc_amount` and rename it to `calc_ask_amount`

Comment (ShadoySV) [reply contracts/pair_stable/src/math.rs:46]: Ok

**Review by wedancedalot — APPROVED** [review]
